[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

# [lib]
# path = "src/lib.rs"

# [[bin]]
# name = "zero2prod"
# path = "src/main.rs"

[dependencies]
actix-web = "4.5.1"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }
